att conda #2

diff --git a/conda.yaml b/conda.yaml
--- a/conda.yaml
+++ b/conda.yaml
@@ -1,7 +1,3 @@
-# For more details on the format and content:
-# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
-# Tip: Adding a link to the release notes of the packages helps maintenance and security.
-
 channels:
   - conda-forge
 
@@ -9,7 +5,6 @@ dependencies:
   - python=3.10.12                # https://pyreadiness.org/3.10
   - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
   - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
-  - google-chrome
   - pip:
     - rpaframework==28.0.0        # https://rpaframework.org/releasenotes.html
     - robocorp==1.4.0             # https://pypi.org/project/robocorp
@@ -19,3 +14,19 @@ dependencies:
     - beautifulsoup4
     - selenium
     - webdriver-manager
+
+# Add this section to manually install Google Chrome
+postRunScripts:
+  - |
+    #!/bin/bash
+    set -e
+    if ! command -v google-chrome &> /dev/null
+    then
+      echo "Google Chrome could not be found, installing..."
+      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
+      sudo apt-get update
+      sudo apt-get install -y google-chrome-stable
+    else
+      echo "Google Chrome is already installed"
+    fi
